version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/ci"
      - "/deploy"
      - "/prepare-env"
    schedule:
      interval: "weekly"
    groups:
      actions-major:
        update-types:
          - "major"
      actions-minor-patch:
        update-types:
          - "minor"
          - "patch"
