version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/ci"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/deploy"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/prepare-env"
    schedule:
      interval: "daily"
