name: Do CI
description: Do build check

inputs:
  target:
    description: Target to build
    required: true
    default: "html"
  env:
    description: Environment variables
    required: false
    default: ""
  upload_artifact:
    description: Upload artifact
    required: false
    default: false
  stop-on-warning:
    description: Stop with error on warnings
    required: true
    default: true

runs:
  using: "composite"
  steps:
    - name: Clean build
      shell: bash
      run: rm -rf _build warning.txt

    - name: 🚀 Build CI
      shell: bash
      env:
        MAKE_TARGET: ${{ inputs.target }}
        MAKE_ARGS: ${{ inputs.env }}
        STOP_ON_WARNING: ${{ inputs.stop-on-warning }}
      run: |
        make "$MAKE_TARGET" $MAKE_ARGS 2> >(tee warning.txt)
        if [[ -s warning.txt ]]; then
          echo ---------------------- Found warnings in build ----------------------
          if [[ "$STOP_ON_WARNING" == "true" ]]; then
            exit 100
          fi
        fi

    - name: ℹ️ Upload artifacts
      uses: actions/upload-artifact@v7
      if: ${{ inputs.upload_artifact=='true' }}
      with:
        name: HTMLOutput
        path: |
          _build/html
